### ISSUE TITLE
Add distance Jacobians and residuals

### ISSUE THREAD

**Issue by mmmarinho** [dqrobotics/matlab#15]
Hello, Bruno,

(This issue depends on #11  and #12 )

**Task list**
- [x] `point_to_point_distance_jacobian` and `point_to_point_residual`
- [x] `point_to_line_distance_jacobian` and `point_to_line_residual`
- [x] `point_to_plane_distance_jacobian` and `point_to_plane_residual`
- [x] `line_to_point_distance_jacobian` and `line_to_point_residual`
- [x] `line_to_line_distance_jacobian` and `line_to_line_residual`
- [x] `plane_to_point_distance_jacobian` and `plane_to_point_residual` 

**Suggestion**
Add the distance Jacobians and residuals of [Dynamic Active Constraints for Surgical Robots using Vector Field Inequalities](https://arxiv.org/abs/1804.11270) to the dqrobotics MATLAB.

I implemented a preliminary version in C++ with the following signatures in the `DQ_robotics` namespace:
```
MatrixXd point_to_point_distance_jacobian(const MatrixXd& translation_jacobian, const DQ& robot_point_translation, const DQ& workspace_point_translation);
double   point_to_point_residual         (const DQ& robot_point_translation, const DQ& workspace_point_translation, const DQ& workspace_point_translation_derivative);

MatrixXd point_to_line_distance_jacobian (const MatrixXd& translation_jacobian, const DQ& robot_point_translation, const DQ& workspace_line);
double   point_to_line_residual          (const DQ& robot_point_translation, const DQ& workspace_line, const DQ& workspace_line_derivative);

MatrixXd point_to_plane_distance_jacobian(const MatrixXd& translation_jacobian, const DQ& robot_point_translation, const DQ& workspace_plane);
double   point_to_plane_residual         (const DQ& robot_point_translation, const DQ& plane_derivative);

MatrixXd line_to_point_distance_jacobian (const MatrixXd& line_jacobian, const DQ& robot_line, const DQ& workspace_point_translation);
double   line_to_point_residual          (const DQ& robot_line, const DQ& workspace_point_translation, const DQ& workspace_point_translation_derivative);

MatrixXd line_to_line_distance_jacobian  (const MatrixXd& line_jacobian, const DQ& robot_line, const DQ& workspace_line);
double   line_to_point_residual          (const DQ& robot_line, const DQ& workspace_line, const DQ& workspace_line_derivative);

MatrixXd plane_to_point_distance_jacobian(const MatrixXd& plane_jacobian, const DQ& robot_plane, const DQ& workspace_point);
double   plane_to_point_residual         (const DQ& robot_plane, const DQ& workspace_point_derivative);
```

Please let me know what you think.

Kind regards,
Murilo

**Comment by bvadorno** [comment]
Hi, @mmmarinho.

The signatures are fine, although I found the variable names a little (unnecessarily) verbose. For instance, `robot_point_translation` can be named as `robot_point` without losing any relevant information.

Furthermore, the implementation should make use of the utility functions mentioned in [#14](https://github.com/dqrobotics/cpp/issues/14), mainly the one used for casting a `DQ` to double.
